-- db/schema.sql — UserRequirements storage for the contact form.
--
-- The requirement document specifies SQL Server (UNIQUEIDENTIFIER / NEWID() /
-- ISJSON). The site runs on Hostinger shared hosting, which serves MySQL, so
-- the same model is expressed here in MySQL 8 terms:
--   UNIQUEIDENTIFIER -> CHAR(36) holding a v4 GUID generated by PHP
--   NVARCHAR(n)      -> VARCHAR(n) on utf8mb4
--   NVARCHAR(MAX)    -> LONGTEXT
--   ISJSON(...) = 1  -> CHECK (JSON_VALID(...))
--   SYSUTCDATETIME() -> UTC_TIMESTAMP(6)

CREATE TABLE IF NOT EXISTS UserRequirements (
    UserRequirementId  CHAR(36)      NOT NULL,

    Name               VARCHAR(200)  NOT NULL,
    Company            VARCHAR(200)  NULL,
    Email              VARCHAR(320)  NOT NULL,
    Phone              VARCHAR(50)   NULL,
    PhoneCountryCode   VARCHAR(10)   NULL,
    PhoneNumber        VARCHAR(30)   NULL,
    PhoneNormalized    VARCHAR(30)   NULL,

    Industry           VARCHAR(200)  NULL,
    SolutionRequired   VARCHAR(500)  NULL,
    EstimatedBudget    VARCHAR(200)  NULL,
    ProjectTimeline    VARCHAR(200)  NULL,
    ProjectDescription LONGTEXT      NOT NULL,

    -- Every field of the submission, including the attachment metadata.
    RequirementDetails LONGTEXT      NOT NULL,

    -- Contact identity used to find an existing record: normalized
    -- name + email + phone, hashed so it can carry a unique index.
    ContactKey         CHAR(64)      NOT NULL,

    AttachmentId       CHAR(36)      NULL,
    AttachmentFileName VARCHAR(255)  NULL,
    AttachmentPath     VARCHAR(1000) NULL,
    -- Pending | Uploaded | Failed
    AttachmentStatus   VARCHAR(20)   NULL,

    CreatedDate        DATETIME(6)   NOT NULL DEFAULT (UTC_TIMESTAMP(6)),
    ModifiedDate       DATETIME(6)   NULL,

    CONSTRAINT PK_UserRequirements PRIMARY KEY (UserRequirementId),
    CONSTRAINT UQ_UserRequirements_ContactKey UNIQUE (ContactKey),
    CONSTRAINT CHK_UserRequirements_RequirementDetails
        CHECK (JSON_VALID(RequirementDetails))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE INDEX IX_UserRequirements_Email ON UserRequirements (Email);

-- Previous versions of a record, written before every update.
CREATE TABLE IF NOT EXISTS UserRequirementsAudit (
    AuditId            BIGINT        NOT NULL AUTO_INCREMENT,
    UserRequirementId  CHAR(36)      NOT NULL,

    Name               VARCHAR(200)  NOT NULL,
    Company            VARCHAR(200)  NULL,
    Email              VARCHAR(320)  NOT NULL,
    Phone              VARCHAR(50)   NULL,
    PhoneCountryCode   VARCHAR(10)   NULL,
    PhoneNumber        VARCHAR(30)   NULL,
    PhoneNormalized    VARCHAR(30)   NULL,

    Industry           VARCHAR(200)  NULL,
    SolutionRequired   VARCHAR(500)  NULL,
    EstimatedBudget    VARCHAR(200)  NULL,
    ProjectTimeline    VARCHAR(200)  NULL,
    ProjectDescription LONGTEXT      NOT NULL,

    RequirementDetails LONGTEXT      NOT NULL,
    ContactKey         CHAR(64)      NOT NULL,

    AttachmentId       CHAR(36)      NULL,
    AttachmentFileName VARCHAR(255)  NULL,
    AttachmentPath     VARCHAR(1000) NULL,
    AttachmentStatus   VARCHAR(20)   NULL,

    CreatedDate        DATETIME(6)   NOT NULL,
    ModifiedDate       DATETIME(6)   NULL,
    ArchivedDate       DATETIME(6)   NOT NULL DEFAULT (UTC_TIMESTAMP(6)),

    CONSTRAINT PK_UserRequirementsAudit PRIMARY KEY (AuditId)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE INDEX IX_UserRequirementsAudit_Requirement
    ON UserRequirementsAudit (UserRequirementId);
